default:
  navigation:
    - title: Women
      subtitle: Categories
      url: /t/women
      items:
        - :title: Shalwar Kamiz
          :url: /t/women/shalwar-kamiz
        - :title: Winter Wear
          :url: /t/women/winter-wear
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Men
      subtitle: Categories
      url: /t/men
      items:
        - :title: Shirts
          :url: /t/men/shirts
        - :title: Shalwar Kamiz
          :url: /t/men/shalwar-kamiz
        - :title: Winter Wear
          :url: /t/men/winter-wear
        - :title: Jackets and Coats
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Towels
      subtitle: Categories
      url: /t/towels
      items:
        - :title: Bed Room
          :url: /t/towels/bed-room
        - :title: Kids
          :url: /t/towels/kids
        - :title: Kitchen
          :url: /t/towels/kitchen
